apiVersion: v1
kind: Service
metadata:
  name: cache-sync-service
  namespace: default
  labels:
    app: cache-sync-service
spec:
  type: ClusterIP
  selector:
    app: cache-sync-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
